### ISSUE TITLE
TypeError: init() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by anupjn** [DTOcean/dtocean-electrical#12]
Hello, apologies for another, possible related, error I am seeing when trying to run electrical_run.py example. 

I had to remove the "encoding" argument to the line below and in the other places in the code where the pandas.ExcelFile() was being used. Only then could I run the code. 

Could this change be the cause of - 
https://github.com/DTOcean/dtocean-electrical/issues/11 

***********
Line in code
***********
https://github.com/DTOcean/dtocean-electrical/blob/9ac69a947c02aebf8f4e69ebd5740b062fb7cf9e/examples/electrical_run.py#L36

***********
Error message
***********
runfile('C:/Users/anambiar/DTOceanPlus/DTOcean1_Electrical_System_Architecture/examples/electrical_run.py', wdir='C:/Users/anambiar/DTOceanPlus/DTOcean1_Electrical_System_Architecture/examples')
Reloaded modules: dtocean_electrical, dtocean_electrical.input_utils, dtocean_electrical.optim_codes.power_flow_v2, dtocean_electrical.network.cable, dtocean_electrical.grid.grid_processing, dtocean_electrical._build, dtocean_electrical.network.network, dtocean_electrical.grid, dtocean_electrical.inputs, dtocean_electrical.input_utils.input_tests, dtocean_electrical.optim_codes.umbilical_ajc, dtocean_electrical.optim_codes.optimiser, dtocean_electrical.optim_codes.array_layout, dtocean_electrical.main, dtocean_electrical.output, dtocean_electrical.network.collection_point, dtocean_electrical.optim_codes, dtocean_electrical.grid.grid, dtocean_electrical.input_utils.utils, dtocean_electrical.network.connector, dtocean_electrical.network
2019-07-11 12:51:55,019 - INFO - dtocean_electrical - Begin logging for dtocean_electrical.
Traceback (most recent call last):

  File "<ipython-input-5-9df99109f450>", line 1, in <module>
    runfile('C:/Users/anambiar/DTOceanPlus/DTOcean1_Electrical_System_Architecture/examples/electrical_run.py', wdir='C:/Users/anambiar/DTOceanPlus/DTOcean1_Electrical_System_Architecture/examples')

  File "C:\Users\anambiar\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\anambiar\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 95, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/anambiar/DTOceanPlus/DTOcean1_Electrical_System_Architecture/examples/electrical_run.py", line 36, in <module>
    xls_file = pd.ExcelFile(os.path.join(data_dir, file_name), encoding = 'utf-8')

TypeError: __init__() got an unexpected keyword argument 'encoding'

**Comment by H0R5E** [comment]
Hi, I can't reproduce your errors, so I am almost certain this is an installation problem. It looks like you have used anaconda to install the code - which procedure did you follow?

With your working environment activated can you post the results of the commands `conda info` and `conda list`. Also if you can find the `.condarc` file in the root of the environment (looks like `C:\Users\anambiar\AppData\Local\Continuum\anaconda3\envs\py2`) and post that it would be helpful.

**Comment by anupjn** [comment]
That might explain things. I did not "install" the electrical package. I downloaded the folder from GitHub and tried to run the example electrical_run.py code directly from within the IDE. When I ran it the first time, Python complained of missing packages and I installed these manually using conda. 

I looked for the .condarc file but could not find the one for Python 2.7 anywhere.

*************
conda info results
*************
(py2) C:\>conda info

     active environment : py2
    active env location : C:\Users\anambiar\AppData\Local\Continuum\anaconda3\en
vs\py2
            shell level : 2
       user config file : C:\Users\anambiar\.condarc
 populated config files : C:\Users\anambiar\.condarc
          conda version : 4.7.5
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\Users\anambiar\AppData\Local\Continuum\anaconda3  (
writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\anambiar\AppData\Local\Continuum\anaconda3\pk
gs
                          C:\Users\anambiar\.conda\pkgs
                          C:\Users\anambiar\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\anambiar\AppData\Local\Continuum\anaconda3\en
vs
                          C:\Users\anambiar\.conda\envs
                          C:\Users\anambiar\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/3.7.3 Windows/7 Wi
ndows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False

*************
conda list results
*************
(py2) C:\>conda list
packages in environment at C:\Users\anambiar\AppData\Local\Continuum\anaconda3
\envs\py2:

Name                    Version                   Build  Channel
alabaster                 0.7.12                   py27_0
asn1crypto                0.24.0                   py27_0
astroid                   1.6.5                    py27_0
attrs                     19.1.0                   py27_1
babel                     2.7.0                      py_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.5                      py27_1
backports.shutil_get_terminal_size 1.0.0                    py27_2
backports_abc             0.5                        py_0
blas                      1.0                         mkl
bleach                    3.1.0                    py27_0
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.3.9                 py27_0    conda-forge
cffi                      1.12.3           py27hcfb25f9_0
chardet                   3.0.4                    py27_1
cloudpickle               1.1.1                      py_0
colorama                  0.4.1                    py27_0
configobj                 5.0.6                    py27_1
configparser              3.7.4                    py27_0
cryptography              2.4.2            py27hc64555f_0
cycler                    0.10.0                     py_1    conda-forge
decorator                 4.4.0                    py27_1
defusedxml                0.6.0                      py_0
descartes                 1.1.0                      py_3    conda-forge
docutils                  0.14             py27h8652d09_0
entrypoints               0.3                      py27_0
enum34                    1.1.6                    py27_1
freetype                  2.10.0               hd7a5a12_0    conda-forge
functools32               3.2.3.2                  py27_1
futures                   3.2.0                    py27_0
geos                      3.6.2                h2880e7c_3    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 h2aa20d9_1
idna                      2.8                      py27_0
imagesize                 1.1.0                    py27_0
intel-openmp              2019.4                      245
ipaddress                 1.0.22                   py27_0
ipykernel                 4.10.0                   py27_0
ipython                   5.8.0                    py27_0
ipython_genutils          0.2.0            py27hbe997df_0
isort                     4.3.20                   py27_0
jedi                      0.13.3                   py27_0
jinja2                    2.10.1                   py27_0
jpeg                      9b                   ha175dff_2
jsonschema                3.0.1                    py27_0
jupyter_client            5.2.4                    py27_0
jupyter_core              4.4.0                    py27_0
keyring                   18.0.0                   py27_0
kiwisolver                1.0.1           py27hdc96acc_1002    conda-forge
lazy-object-proxy         1.4.1            py27h0c8e037_0
libblas                   3.8.0                     8_mkl    conda-forge
libcblas                  3.8.0                     8_mkl    conda-forge
liblapack                 3.8.0                     8_mkl    conda-forge
libpng                    1.6.37               h7a46e7a_0
libsodium                 1.0.16               h8b3e59e_0
markupsafe                1.1.1            py27h0c8e037_0
matplotlib                2.2.3            py27h8a2030e_1    conda-forge
matplotlib-base           2.2.3            py27hf194043_1    conda-forge
mccabe                    0.6.1                    py27_1
mistune                   0.8.4            py27h0c8e037_0
mkl                       2019.4                      245
mkl_fft                   1.0.12           py27h44c1dab_0
nbconvert                 5.5.0                      py_0
nbformat                  4.4.0            py27hf49b375_0
networkx                  2.2                        py_1    conda-forge
numpy                     1.16.3           py27hab51878_0    conda-forge
numpy-base                1.16.3           py27hb1d0314_0
numpydoc                  0.9.1                      py_0
openssl                   1.0.2r               h0c8e037_0    conda-forge
packaging                 19.0                     py27_0
pandas                    0.24.2           py27hc56fc5f_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py27_1
parso                     0.4.0                      py_0
pathlib2                  2.3.3                    py27_0
pickleshare               0.7.5                    py27_0
pip                       19.1.1                   py27_0
polite                    0.10.0                   py27_0    dataonlygreater
prompt_toolkit            1.0.15           py27h3a8ec6a_0
psutil                    5.6.2            py27h0c8e037_0
pycodestyle               2.5.0                    py27_0
pycparser                 2.19                     py27_0
pyflakes                  2.1.1                    py27_0
pygments                  2.4.2                      py_0
pylint                    1.9.2                    py27_0
pyopenssl                 19.0.0                   py27_0
pyparsing                 2.4.0                      py_0
pypower                   5.1.4                    py27_0    dataonlygreater
pyqt                      5.6.0            py27h6e61f57_6
pyrsistent                0.14.11          py27h0c8e037_0
pysocks                   1.7.0                    py27_0
python                    2.7.16               hcb6e200_0
python-dateutil           2.8.0                    py27_0
pytz                      2019.1                     py_0
pywin32                   223              py27h0c8e037_1
pyyaml                    5.1              py27h0c8e037_0
pyzmq                     18.0.0           py27hc56fc5f_0
qt                        5.6.2            vc9hc26998b_12
qtawesome                 0.5.7                    py27_1
qtconsole                 4.5.1                      py_0
qtpy                      1.7.1                      py_0
requests                  2.22.0                   py27_0
rope                      0.14.0                     py_0
scandir                   1.10.0           py27h0c8e037_0
scipy                     1.2.1            py27h4c3ab11_0
setuptools                41.0.1                   py27_0
shapely                   1.6.4           py27hc31c106_1000    conda-forge
simplegeneric             0.8.1                    py27_2
singledispatch            3.4.0.3          py27h3f9d112_0
sip                       4.18.1           py27hc56fc5f_2
six                       1.12.0                   py27_0
snowballstemmer           1.2.1            py27h28d3bf7_0
sphinx                    1.8.5                    py27_0
sphinxcontrib             1.0                      py27_1
sphinxcontrib-websupport  1.1.2                      py_0
spyder                    3.3.4                    py27_0
spyder-kernels            0.4.4                    py27_0
sqlite                    3.28.0               h0c8e037_0
testpath                  0.4.2                    py27_0
tornado                   5.1.1            py27h0c8e037_0
traitlets                 4.3.2            py27h1b1b3a5_0
typing                    3.6.6                    py27_0
urllib3                   1.24.2                   py27_0
vc                        9                    h7299396_1
vs2008_runtime            9.00.30729.1         hfaea7d5_1
wcwidth                   0.1.7            py27hb1a0d82_0
webencodings              0.5.1                    py27_1
wheel                     0.33.4                   py27_0
win_inet_pton             1.1.0                    py27_0
win_unicode_console       0.5              py27hc037021_0
wincertstore              0.2              py27hf04cefb_0
wrapt                     1.11.1           py27h0c8e037_0
xlrd                      1.2.0                      py_0    conda-forge
yaml                      0.1.7                h3e6d941_2
zeromq                    4.3.1                h2880e7c_3
zlib                      1.2.11               h3cc03e0_3

(py2) C:\>

**Comment by H0R5E** [comment]
The DTOcean packages are very sensitive to their dependencies. They are finely balanced to ensure that the whole system works together (particularly for the Qt4 dependency of the GUI, but for other packages as well). I recommend you follow the installation procedure for the source code written in the README here:

https://github.com/DTOcean/dtocean-electrical#source-code

I see you are running from an ipython console or jupyter notebook. In this case I recommend you use the .condarc file from dtocean-app, rather than the one in this repository. Here is a link:

https://raw.githubusercontent.com/DTOcean/dtocean-app/master/.condarc

EDIT: remember to install / run jupyter into / from the _dtocean_electro environment, e.g.:

```
> activate _dtocean_electro
> conda install jupyter
> start jupyter notebook
```

I would also advice you NOT to update conda to version 4.7.x at the moment, as some of the package downloads are not working properly.

**Comment by anupjn** [comment]
Thank you for the clear instructions. I managed to get the example file run successfully. 

The problems I  was facing was indeed something to do with the versions of the packages I had installed manually.  

Thank you once again.
